import Head from "next/head";
import React from "react";

/**
 * This is the home page
 * @return {JSX.Element}: JSX for the home page
 */
export default function Home() {
  return (
    <Head>
      <title>FretHouse</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
